### ISSUE TITLE
[Request] Ability to disable hud or have add an item to check sanity.

### ISSUE THREAD

**Issue by tencorvids** [Su5eD/Somnia-Awoken#10]
I have a custom "realism" pack with minimal hud elements, and would like to disable the hud element, and use an item to check sanity. Thank you.

**Comment by Su5eD** [comment]
If you want to disable the fatigue display, set `displayFatigue` in the config to nothing. About the sanity checker: I won't be implementing this. I'm sure you can make a mod for your custom pack that makes this possible. Add Somnia as a dependency from cursemaven, then grab `CapabilityFatigue` from the player when the item is used and call `getFatigue` on it.

**Comment by tencorvids** [comment]
Thank you!
