### ISSUE TITLE
Unable to hide fatigue value??

### ISSUE THREAD

**Issue by Aceplante** [Su5eD/Somnia-Awoken#100]
### Describe the bug

The fatigue value is unable to be hidden

### Is this bug related to another mod?

No

### Steps to reproduce

Open config and look for option to disable it.

### Expected Behavior

There should be an option in the config to disable it, but that does not seem to be the case. Im aware I can turn it to text, which at least is better than numbers, but the text looks bad and i do not want it on my screen as it breaks immersion. Perhaps it could only show for a few seconds upon clicking a bed?

**Comment by Su5eD** [comment]
To hide the fatigue display, you can set the client `fatigueDisplayPos` config option to `NONE`.

**Comment by Aceplante** [comment]
None is not a valid option and resets to bottom_right

**Comment by Su5eD** [comment]
What minecraft and somnia version are you using?

**Comment by Aceplante** [comment]
The latest one and 1.18.2

**Comment by Su5eD** [comment]
Looks like the feature was never backported to 1.18.2. Anyway, it's now been added in version `1.18.2-3.0.104`.
