### ISSUE TITLE
[1.18.2] Crash when used with Cold Sweat

### ISSUE THREAD

**Issue by DeshiDesu** [Su5eD/Somnia-Awoken#103]
### Describe the bug

After reaching -100 temperature by sleeping at night, the game crashes and I could no longer relogin. The crash is probably caused by Cold Sweat, but I'll issue it here just in case.

### Is this bug related to another mod?

Cold sweat is a temperature mod for Forge. You take damage after you gain +100 or -100 temperature. Your temperature is affected by your environment (ex: night means cold and day means hot.)

### Steps to reproduce

1. Sleep during night
2. Accumulate -100 temperature 
3. Wait for crash
...

### Expected Behavior

The player should exit the bed after taking temperature damage, but in my case it only crashes.

### Additional context

I've done some testing with only Cold Sweat and Somnia Awoken installed, but I could not replicate this affect. My game only crashes when used alongside my modpack (about 200 mods and more).

Here is the crash log and spark profile for reference.
https://spark.lucko.me/QgtCQJDYK2
[crash-2023-03-30_22.16.00-server.txt](https://github.com/Momo-Studios/Cold-Sweat/files/11117630/crash-2023-03-30_22.16.00-server.txt)

**Comment by Su5eD** [comment]
I made a change to the problematic line of code that should hopefully resolve the issue. Try using the latest build, `3.0.105`.

**Comment by DeshiDesu** [comment]
Thank you I will test it today. Will come back to notify you of the results!

**Comment by DeshiDesu** [comment]
[crash-2023-04-05_20.33.12-server.txt](https://github.com/Su5eD/Somnia-Awoken/files/11165273/crash-2023-04-05_20.33.12-server.txt)
Unfortunately it did not work.

**Comment by Su5eD** [comment]
> java.lang.IllegalArgumentException: Player DeshiDesu is missing a damage model!
   &nbsp;&nbsp;&nbsp;&nbsp;at ichttt.mods.firstaid.common.util.CommonUtils.lambda$getDamageModel$1

This crash looks to be caused by the `First Aid` mod. Please report the issue on their issue tracker.
