### ISSUE TITLE
Somnia Crash on startup

### ISSUE THREAD

**Issue by Drackion** [Su5eD/Somnia-Awoken#104]
### Describe the bug

Somnia crashes modpack shortly after launch

### Is this bug related to another mod?

Not sure

### Steps to reproduce

1. Download Somnia 1.19.2 on GDL 
2. Launch instance
3. Crash

### Expected Behavior

not to crash on startup

### Additional context

Nothing about the crash appears in latest.log and no crash report is made the only info about the crash in the GLD error popup

![image](https://user-images.githubusercontent.com/64641342/230804823-e447586b-ff88-4b5a-8d52-8ec52c0e5226.png)
![image](https://user-images.githubusercontent.com/64641342/230804833-420c14c5-f01d-4960-988f-3552a3ed43b3.png)
![image](https://user-images.githubusercontent.com/64641342/230804842-d82a1e3e-1051-42d2-92f0-eb68e328b3d1.png)
![image](https://user-images.githubusercontent.com/64641342/230804845-84925f21-1c73-4c3b-bf77-23ea8e0d2382.png)
![image](https://user-images.githubusercontent.com/64641342/230804857-d5278ddc-8e2b-49dc-b9a9-5e3801330d82.png)
![image](https://user-images.githubusercontent.com/64641342/230804863-998ba545-b861-4f68-9d0e-94ab61696ea2.png)
![image](https://user-images.githubusercontent.com/64641342/230804874-235f3e62-2a78-44be-b231-3ce6ec339a13.png)
![image](https://user-images.githubusercontent.com/64641342/230804882-01c333e7-b9bd-4168-b89d-28990ea6332f.png)
![image](https://user-images.githubusercontent.com/64641342/230804890-2735d341-1304-4377-a5e3-ad95092af2cf.png)
![image](https://user-images.githubusercontent.com/64641342/230804897-dbb85495-7c61-4283-93eb-cee8d1a72621.png)

**Comment by Su5eD** [comment]
Fixed in Somnia `1.19.2-3.1.6` and Koremods `0.6.1`
