### ISSUE TITLE
Modded beds compatibility

### ISSUE THREAD

**Issue by Su5eD** [Su5eD/Somnia-Awoken#17]
**Post all requests regarding modded beds compat here.** 

The following beds are currently supported:
| Bed | Mod | Support type |
| ------ | ------- | -------------------- |
| Cryogenic Chamber | [Galacticraft](https://www.micdoodle8.com/mods/galacticraft) | Bugfree |
| Bed Cart | [Railcraft](https://www.curseforge.com/minecraft/mc-mods/railcraft) | Supported |
| Bunk Bed | [Industrial Renewal](https://www.curseforge.com/minecraft/mc-mods/industrial-renewal) | Compatible |
| No Save Bed | [Heat and Climate](https://www.curseforge.com/minecraft/mc-mods/heat-and-climate) | Compatible |
| <Hammocks\> | [Comforts](https://www.curseforge.com/minecraft/mc-mods/comforts) | Bugfree |

**Interactions**:

| Item | Mod | Support type |
| ------- | ------- | -------------------- |
| Sleep Charm | [Dark Utilities](https://www.curseforge.com/minecraft/mc-mods/dark-utilities) | Bugfree |
| Sleeping Bag | [OpenBlocks](https://www.curseforge.com/minecraft/mc-mods/openblocks) | Supported (no WTS) |
| Sleeping Bag | [Sleeping Bags](https://www.curseforge.com/minecraft/mc-mods/sleeping-bags) | Supported (no WTS) |
| <Sleeping Bags\> | [Comforts](https://www.curseforge.com/minecraft/mc-mods/comforts) | Supported (no WTS) |
| Sleeping Mat | [Cyclic](https://www.curseforge.com/minecraft/mc-mods/cyclic) | Supported (no WTS) |

Support types:
- Bugfree - somnia features are unavailable, but the bed/item doesn't cause any issues
- Compatible - all somnia features are available, without any changes to the code
- Supported (no WTS) - simulation only
- Supported - simulation and wake time selection

**Comment by Darkmega18** [comment]
Comforts would be something worth looking into. got sleeping mats and a day sleeping hammock.

possibly also cyclics sleeping bag/bedroll item.

and inventory pets sleeping in inventory pet bed.

**Comment by Cixon** [comment]
> Comforts would be something worth looking into. got sleeping mats and a day sleeping hammock.
> 
> possibly also cyclics sleeping bag/bedroll item.
> 
> and inventory pets sleeping in inventory pet bed.

yes please comforts!
