### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by aaronhowser1** [Su5eD/Somnia-Awoken#19]
https://pastebin.com/dBWXpz5r

![image](https://user-images.githubusercontent.com/15698722/90851841-83152c80-e33b-11ea-9ca9-155c9367455e.png)

**Comment by Su5eD** [comment]
Can it be reproduced?

**Comment by Based199** [comment]
I can't reproduce it so maybe just a one time thing. I'll play with it some more to make sure.

**Comment by Su5eD** [comment]
Should be fixed in d586ba0
