### ISSUE TITLE
Sleep times are inaccurate

### ISSUE THREAD

**Issue by Titoo8899** [Su5eD/Somnia-Awoken#2]
Hi,
your mod and the Idear is nice but the Time work not Perfect. Then I make with the Clock right click on a bett and click as worldtime "noon" then is the game to fast and I come on a later time up then I not stop the sleep then the Clock was with the sun in the middle.
I hope you can the Synchron of your mod fix then I say "noon" and the time then the Person wake up is  16, 17 or 18 o´clock then is it not "noon". And the other think is I hope you can see in Screen one the Hud of the Time and the time speed with more positions add. I think  good then it give "Top Left","Top Middle" and "Top Right".

![2020-08-08_18 19 07](https://user-images.githubusercontent.com/42325138/89715243-b4d5dd00-d9a4-11ea-973c-5aeca0680012.png)

![2020-08-08_18 19 07](https://user-images.githubusercontent.com/42325138/89715216-9a036880-d9a4-11ea-9401-4b985b238c77.png)

**Comment by Titoo8899** [comment]
Hi, 
this screen have I miss to add. It show the time when the bed have me wake up then I have "noon" have click. And this show the time not to 100% synchron.
![2020-08-08_18 26 17](https://user-images.githubusercontent.com/42325138/89716372-aa1f4600-d9ac-11ea-9ef6-6125e79d16ae.png)

**Comment by Su5eD** [comment]
Ability to change sleep ETA display has been added in 02ba12b

**Comment by Titoo8899** [comment]
Hi, thanks to add the ETA Display position. The 2 think have you good make. But I hope you can the time Synchron better make in the next update what the time of "noon" and the other times better start and end then we sleep. Why I find then I go in the Bed the time is not so fast or not so slow to make the time perfect who we wake up. I hope this can you fix.

**Comment by Su5eD** [comment]
It's being worked on

**Comment by Titoo8899** [comment]
Hi, I have make a Video about the Problem with the Synchron of the Worldtime and your Mod. And I have the link to the Mod who you can the worldtime see.
Links:
1. IgniteHud Version: 1.12 - Beta 0.5.4 from Owner Deadzoke: https://www.curseforge.com/minecraft/mc-mods/ignitehud 

2. My Youtubevideo of the Problem: https://www.youtube.com/watch?v=x136OzHEBjc

I hope this 2 links help you to fix the Synchron Problem of Sleep begin and Sleep end with the right Minecraft ingame time.

**Comment by Su5eD** [comment]
The wake time was being updated after you selected a custom one. This has been fixed in c994bdf. However, wake times can still mess up if the world is running a few ticks behind. In case this happens, try playing around with the performance config options. Using performance mods may also help.
