### ISSUE TITLE
Hostile mob spawn in bed is open to sky

### ISSUE THREAD

**Issue by jackg2527** [Su5eD/Somnia-Awoken#21]
Hi, love this mod for survival. using it without fatigue feature...no more escaping night by sleeping in the open! What about an option to have hostile mob(s) spawn near/on the player if sleeping at night AND bed is open to the sky? This way you have to seek shelter at night or there will be trouble. I thought maybe earlier version of mod did this? Thanks in advance for considering this request!

**Comment by Su5eD** [comment]
If you sleep in the open, sped up monsters will quickly kick you outta the bed.
Earlier versions of Minecraft woke you up in the middle of the night with a Zombie/Skeleton by your side if you went to sleep when monsters were nearby.

**Comment by jackg2527** [comment]
OK thanks for the quick reply. And oops that's right it was earlier MC versions. And yes the monsters are doing a fine job of interrupting sleep :) Was thinking extra feature would make cause them to get you even if sleeping 10+blocks off the ground (with no roof). Thanks again, I will close.
