### ISSUE TITLE
Somnia incorrectly calculates wake-up time with Time-Speed mod (Вращение Земли Майнкрафтская)

### ISSUE THREAD

**Issue by V972** [Su5eD/Somnia-Awoken#22]
**Description**
When using a mod called "[Вращение Земли Майнкрафтская](https://www.curseforge.com/minecraft/mc-mods/time-speed-mod)" or more shortly the "Time-Speed mod", a wake up time and a sleeping period isn't adjusted to the time speed modifier, resulting waking up in the middle of the night.

I am using:
Somnia v1.9.7 -- the latest version as of writing this report.
And B3M-1.12.2-17.

**Steps to reproduce the bug:**
1. Have both mods installed;
2. Set ВЗМ's time multiplier to someting greater than 1 (meaning time will go slower, than noemal)
3. Go to sleap.

**Screenshots**
Exsibit A: trying to sleep and wake up at 7:30 results only a half a hour progression.
![2020-08-26_00 02 10](https://user-images.githubusercontent.com/45125685/91228193-82600a00-e730-11ea-83c0-73d5c94a4c93.png)
--------------------------------
![2020-08-26_00 02 18](https://user-images.githubusercontent.com/45125685/91228376-ce12b380-e730-11ea-948d-c873d349a4e5.png)
--------------------------------
![2020-08-26_00 02 24](https://user-images.githubusercontent.com/45125685/91228395-d66aee80-e730-11ea-8959-258e3c799b86.png)

**Comment by V972** [comment]
Just sleaping in the bed bugs out too.
I go to bed at 19-20, but wake up at 5-5:30

**Comment by Su5eD** [comment]
The mod appears to freeze time throughout the day. There is nothing I can do about this, sorry.
