### ISSUE TITLE
If side effects are disabled, and Fatigue disappears when >20, it should say "not tired" in the GUI text

### ISSUE THREAD

**Issue by aaronhowser1** [Su5eD/Somnia-Awoken#26]
**Is your feature request related to a problem? Please describe.**
Pretty much every new player, before finding the quest but noticing the Fatigue, comes to the discord to ask what it is.

**Describe the solution you'd like**
It should explain itself in the GUI text

**Describe alternatives you've considered**
Instead of showing the number at all, maybe just have in red text "Not Tired" or "Wide Awake" or something

**Comment by Su5eD** [comment]
I added a config option to change the GUI counter to display words instead
