### ISSUE TITLE
An item to stop or reduce fatigue gain besides sleeping.

### ISSUE THREAD

**Issue by UberbeastX** [Su5eD/Somnia-Awoken#27]
**Is your feature request related to a problem? Please describe.**
Recently while I was exploring I started having the effects if not sleeping for a long while and it made me really slow, I knew the mod could do this if I didn't regulate my sleep and I paid the price for it by dying and being sent to my bed. I think it would be cool to have coffee or some other item that can be used to stop fatigue gain or reduce it. 

**Describe the solution you'd like**
I think it would be cool to have coffee or some other item that can be used to stop fatigue gain or reduce it. 

**Describe alternatives you've considered**
I already thought about trying to just reduce the fatigue gain overall but then that just make it pointless to have since it means through no input from me at all I can just go where ever I want and barely worry about fatigue. 

**Additional context**

**Comment by Su5eD** [comment]
I added support for vaious coffees from other mods. You can find a full list [here](https://github.com/Su5eD/Somnia/wiki/Fatigue#reducing-fatigue).

**Comment by UberbeastX** [comment]
Cool thanx
