### ISSUE TITLE
Survive fatigue compat

### ISSUE THREAD

**Issue by EllriNidhogg** [Su5eD/Somnia-Awoken#30]
**Is your feature request related to a problem? Please describe.**
Running Survive causes two sets of fatigue and negative attributes to stack onto my player making it very hard to even get back to my bed. 

**Describe the solution you'd like**
Configure to allow for survives fatigue levels to do the effects so that there aren't stacking effects.

**Describe alternatives you've considered**
Possibly use the fatigue system from fatigue only for effects because I rather like being able to sleep at odd times if I need to stay up for something.
Potentially this might also need further tweaking when there is a sleep vote system like Morpheus in play.

**Additional context**

**Comment by Su5eD** [comment]
I can't seem to find any references to "fatigue" in survive's code. Are you sure it's called that way?

**Comment by Su5eD** [comment]
Closing as stale
