### ISSUE TITLE
Server does not seem to like "Don't process lighting and sounds" option

### ISSUE THREAD

**Issue by Darkmega18** [Su5eD/Somnia-Awoken#40]
**What version of Somnia Awoken are you using?**
1.11-beta

**Describe the bug**  
While on the server when somnia based sleeping is engaged and disableMoodSoundAndLightChecks is enabled (it's enabled in my pack and so transfers to the server as I just the configs 1 for 1 across to it when testing) server continually pops "unexpected errors" from vanilla fix while sleeping over and over. My crash log folder is full of these:
[crash-2021-03-29_23.03.05-client.txt](https://github.com/Su5eD/Somnia/files/6221727/crash-2021-03-29_23.03.05-client.txt)

Server also had this at some point:
[crash-2021-03-29_07.41.59-server.txt](https://github.com/Su5eD/Somnia/files/6221784/crash-2021-03-29_07.41.59-server.txt)

not sure if related cause the server has a different timezone and it wasn't the same timestamp, but it is about time and lighting and I did have a crash soon after the spam ended when the bed automatically woke me up that closed the server but said nothing on client:

**Is this bug related to another mod?**  
Probably not? 

**To Reproduce**  
Steps to reproduce the bug:
1. Sleep on server with disableMoodSoundAndLightChecks
2. Also have some furnaces etc going.
3. Sleep and let it get towards daytime so light starts changing also.
4. Have vanilla fix and catch some bugs...?

**Expected behavior**  
Sleep should work fine without errors.

**Screenshots**  
Tried to reproduce just now but didn't reoccur so it's another one of those "heisenbugs". :V

**Additional context**  
was sleeping in a wizard tower next to a warehouse and enchanter and some furnaces which were running at the time. In tests just now furnaces weren't active. so maybe it was the crackling and related nearby sounds and accelerations.

**Comment by Su5eD** [comment]
Does this happen without vanilla fix? I can see a possible incompatibility here, since it's a coremod.

**Comment by Darkmega18** [comment]
turns out, it was actually turned villagers who were approaching us on the server. they'd proc random issues server side related to their sounds and would coincidentally rock up when I'm trying to sleep sometimes. which explained the inconsistency of it again. it just felt like sound related to this cause I'd be in or near the bed when it'd start happening till it occurred some more while exploring later. :V
