### ISSUE TITLE
[1.12.2] Vanilla Sleeping, but not actually sleeping, resets fatigue as if the sleep occurred

### ISSUE THREAD

**Issue by Darkmega18** [Su5eD/Somnia-Awoken#42]
**What version of Somnia Awoken are you using?**
The version of Somnia Awoken you're playing.
Somnia 1.11 beta, latest shown on curseforge for 1.12.2

**Describe the bug**  
When you sleep on the server, but others aren't sleeping yet if you get up from the state of being in sleep, when you wake up it treats you as having slept already, and refreshes your fatigue without actually resetting the day.

**Is this bug related to another mod?**  
I don't believe so? but there is the Quark sleep vote in there which alerts everyone that you're currently napping or sleeping. But it's set to be 100% required, so it's just a counter at this point.

**To Reproduce**  
Steps to reproduce the bug:
1. Get on Server with someone else.
2. Have one person go to sleep vanilla style (shift sleep). but have the other stay up.
3. When you're fully settled into bed, get up from it, and fatigue will get reloaded as if you slept, but no time will have passed.

**Expected behavior**  
I'd just get up like normal without fatigue being reset. but instead it gets reset and now I can't sleep when friend gets to the bed and we gotta stay up through the super dark hardcore darkness new moon night. :V

**Screenshots**  
Not really applicable.

**Additional context**  
Modpack: "Where the Wind Shall Carry you", aka, my modpack. lots of mods. not completely sure if it's a cross issue or not.

**Comment by Su5eD** [comment]
Looks like I'm missing a daytime check
