### ISSUE TITLE
Timer for messages

### ISSUE THREAD

**Issue by axalox** [Su5eD/Somnia-Awoken#43]
Hello, nice idea

There is a message that i can't read because it doesn't as long as i can read it.
Could you add an option for timer for this message ?

**Comment by Su5eD** [comment]
What message do you mean? Please format your issue in a clearer way

**Comment by axalox** [comment]
I play with a modded version
Sometimes i wake up in night with a message saying there is some noises, but it's timing is too fast for read it easily

**Comment by Su5eD** [comment]
These are hotbar messages added by vanilla, so I can't really change their duration, sorry. If you're having trouble reading the whole message, you can take a look at all possible messages in the [translation file](https://github.com/Su5eD/Somnia/blob/d5d7679d183d5db42b5f2e2c13612c4a62d1ca27/src/main/resources/assets/somnia/lang/en_us.json#L11-L16).
