### ISSUE TITLE
Sleeping visual bug

### ISSUE THREAD

**Issue by juraj-hrivnak** [Su5eD/Somnia-Awoken#45]
**What version of Somnia Awoken are you using?**
```
Minecraft 1.12.2
Forge-14.23.5.2855
Somnia 1.11 Beta 2
```
**Describe the bug**  
- Only visual bug. It doesn't affect functionality.

**Is this bug related to another mod?**
- Modlist included in the latest.log
https://paste.ee/p/uGWzv
> I will test it alone. In very near future :D

**To Reproduce**  
Sleep in any bed (including modded ones)

**Screenshots**  
![2021-04-27_14 09 00](https://user-images.githubusercontent.com/71150936/116242839-9dbf6100-a766-11eb-8027-15ed5a7f42e4.png)
![2021-04-27_14 09 32](https://user-images.githubusercontent.com/71150936/116242843-9ef08e00-a766-11eb-9b55-be821c4f0f6f.png)
![2021-04-27_14 10 08](https://user-images.githubusercontent.com/71150936/116242846-9f892480-a766-11eb-8c0c-d01df49d45b6.png)
![2021-04-27_14 11 49](https://user-images.githubusercontent.com/71150936/116243042-d101f000-a766-11eb-8c00-78e5782be52b.png)

**Comment by juraj-hrivnak** [comment]
Oh, sorry, I now realized this was already fixed/reported.
So, I'm closing it.

**Comment by Su5eD** [comment]
No worries, it confuses a lot of people. I should find a way to notify them about this...
