### ISSUE TITLE
Effect 1 & 3 won't be cleared on wake-up in the 1.12.2 version

### ISSUE THREAD

**Issue by usernameye** [Su5eD/Somnia-Awoken#49]
Screwed around with the config, setting debuffs to 100000 (infinite in-game) since I found out they disappear on wake-up (making it realistic), but only side effects 2 & 4 disappear on wake-up, and there isn't much control on 4 as it lasts only until you sleep by default.

**Comment by Su5eD** [comment]
What version of Somnia are you using? Also, can you show what exactly you changed in the config?

**Comment by usernameye** [comment]
Latest version. I changed the duration to 100000.
I:sideEffectStage2Duration=100000

**Comment by Su5eD** [comment]
Latest beta or release?
If on beta, that option doesn't exist anymore, try re-generating your config file.

**Comment by usernameye** [comment]
Ops, my bad. I meant the last update for 1.12.2.
Forge 1.12.2: somnia-1.10.2

**Comment by Su5eD** [comment]
I suggest you to update to the latest beta, which adds a new side effect config. With that, you'll be able to customize the ranges of each side effect stage, and even add you own ones.

> I found out they disappear on wake-up (making it realistic)

Once your fatigue drops below the range of a side effect stage, it disappears, yes. 
You can adjust the ranges of the stages and lower the fatigue replenish rate if you want a more difficult experience.
