### ISSUE TITLE
Somnia GUI nonfunctional

### ISSUE THREAD

**Issue by aaronhowser1** [Su5eD/Somnia-Awoken#5]
It says it provides an "enhanced sleeping gui," but it just looks normal to me

![image](https://user-images.githubusercontent.com/15698722/89721270-46435000-d9a1-11ea-88a9-d996263b264e.png)

**Comment by Su5eD** [comment]
Looks like each time I try to replace their gui, MineTogether just cancels the event. Plan B would be to draw on the screen without opening a gui
