### ISSUE TITLE
Phantoms don't spawn in overworld

### ISSUE THREAD

**Issue by D-Bigboy-302** [Su5eD/Somnia-Awoken#51]
### Describe the bug

When Somnia is installed phantoms do not spawn in the overworld when the player doesn't sleep.

### Is this bug related to another mod?

No. This happens even with no other mods.

### Steps to reproduce

1. Load world with somnia
2. Don't sleep (any configuration with somnia)
3. Behold the lack of phantoms!

### Expected Behavior

Phantoms to spawn in overworld.

### Additional context

Forge: 1.16.5-36.1.0
Mod version: 2.1.1-beta.2

**Comment by Su5eD** [comment]
How long have you been without sleep? The likelihood of Phantoms spawning is really small on the first days.
> The chance of a successful spawn is x−72000⁄x, where x is the number of ticks since the player last entered a bed or died. This roughly comes to a 1⁄4 (**25.0%**) chance on day 4, a 2⁄5 (**40.0%**) chance on day 5, a 3⁄6 (1⁄2) (**50.0%**) chance on day 6, 4⁄7 (**about 57.1%**) chance on day 7, and so on.

**Comment by D-Bigboy-302** [comment]
I've gone 13 minecraft days without sleeping and still haven't come across any phantoms. I'll go do some more testing and give a log, just in case I've overlooked something

**Comment by Su5eD** [comment]
Tested this in the dev environment. I left the game open with time frozen at night, and when I came back later (60 - 90 mins), I was already slain by a Phantom.

**Comment by D-Bigboy-302** [comment]
Huh. I must have really bad luck. Or in this case, good luck for not having to deal with phantoms. Well my apologies for bothering u with an issue most likely on my end.

**Comment by Su5eD** [comment]
Maybe you could check if the `doInsomnia` gamerule is enabled
