### ISSUE TITLE
Player stands on bed (no laying animation and sleeping gui) and cannot exit the bed unless bed is broken, in the Might and Mine modpack (Somnia 1.11 beta 2)

### ISSUE THREAD

**Issue by PorkingGit** [Su5eD/Somnia-Awoken#52]
### Describe the bug

The title

### Steps to reproduce

1.Sleep in bed
2.
3.
...

**Comment by Su5eD** [comment]
This looks to be caused by an incompatibility with the [Let Me Sleep](https://www.curseforge.com/minecraft/mc-mods/let-me-sleep) mod. Try removing it and test again
