### ISSUE TITLE
Standing in bed, unable to move and don't wake up right, have to break bed.

### ISSUE THREAD

**Issue by Tskuno** [Su5eD/Somnia-Awoken#61]
### Describe the bug

If you go to sleep for some reason you stand in the bed, time speeds up, but you don't wake up no matter what time you pick. You end up having to break the bed or you stay stuck.

### Is this bug related to another mod?

https://www.curseforge.com/minecraft/modpacks/infected-dungeons

### Steps to reproduce

1. Sleep in bed
2. Sleep in bed with a clock
3. 
...

### Expected Behavior

Inability to move, wake up or do much of anything. You have to break the bed. 

### Additional context

https://www.curseforge.com/minecraft/modpacks/infected-dungeons

This is a custom modpack I am working on. I do not have the mod you listed as incompatible. But if I had to take a guess it's either Morpheus(but you say it should work) or tough as nails/first aid. As that provides healing in bed.

**Comment by Tskuno** [comment]
this is 1,12,2

**Comment by Su5eD** [comment]
Can you please do some testing and identify the mod causing the issue? Also, which version of somnia are you using?

**Comment by Tskuno** [comment]
I've tried the nonbeta version, that is, the latest version 1.10. and the current beta version. I am running through testing right now. turned off Morpheus first as it should be the only other mod that has the ability to affect sleep, if that's not the cause then I'll try the one that affects healing when sleeping, which is either first aid or rough tweaks. then I will try tough as nails. those are my bigger guesses as to what could cause a conflict. also if possible would you be able to add an option to configure normal sleep(aka keep the fatigue system, but disable the custom sped up sleep)?

**Comment by Tskuno** [comment]
So, removing Morpheus fixed part of the issue. I can sleep if I don't have a clock in my hand. but if I sleep with a clock in my hand and sneak+rightclicking seems to put me in the state I described above.

**Comment by Tskuno** [comment]
Ok, I have managed to make it happen everytime now. It's when you go to sleep via right click. It doesn't let you out of the bed. time just keeps speeding up no matter what

**Comment by Tskuno** [comment]
Unless you break the bed

**Comment by Tskuno** [comment]
So, it seems to be specific for sleeping at nighttime. Upon sleeping at night, no matter what I'm doing it will put me in the stand-up position, and I cannot move away from the bed(it jerks be back), I will continue to remove mods to test which is causing this. But it's a consistent issue now. Sleeping during the day is fine.

**Comment by Su5eD** [comment]
I tested morpheus (in singleplayer), and it works without any issues using a clock at night.

> add an option to configure normal sleep(aka keep the fatigue system, but disable the custom sped up sleep)

Isn't this what vanilla sleep does?

**Comment by Tskuno** [comment]
I more want ~just~ the fatigue system that makes you need to rest else conditions happen(and with the ability for items to deter the fatigue)

**Comment by Tskuno** [comment]
So, mod that conflicts is random tweaks. for some reason with this mod on it causes the issue that if you try to sleep at night with somnia it will prevent the somnia config from activating and just result in you being stuck in the bed.(it does still cause time to rapidly pass however.)

**Comment by Tskuno** [comment]
Thank you for your time.

**Comment by FrijDom** [comment]
I don't know if anyone else is having this problem, but I discovered the cause and fix within the random tweaks mod. Random Tweaks allows you to disable certain features that normally prevent sleep, and having them active causes it to hijack the sleep function at night. If you turn them off in the config, it should stop this problem from happening.
