### ISSUE TITLE
clock bug

### ISSUE THREAD

**Issue by nitbe** [Su5eD/Somnia-Awoken#62]
### Describe the bug

Use the clock to go to bed at regular intervals and wake up at different times

### Is this bug related to another mod?

no

### Steps to reproduce

1.When I set the clock to wake up at 6 am, I fell asleep until about 8 pm
2.When I sleep, the pig next to me will break free from the fence and escape
3.
...

### Expected Behavior

fix

**Comment by Su5eD** [comment]
> 2. When I sleep, the pig next to me will break free from the fence and escape

Can you provide more details about this step?

**Comment by nitbe** [comment]
> > 1. 当我睡觉时，我旁边的猪会挣脱围栏逃跑
> 
> 您能否提供有关此步骤的更多详细信息？
I found the pig’s problem. It was caused by the bigbrain mod.
