### ISSUE TITLE
Add food to increase fatigue

### ISSUE THREAD

**Issue by nitbe** [Su5eD/Somnia-Awoken#63]
### Is your feature request related to a problem? Please describe.

Add options to allow food to increase fatigue

### Describe the solution you'd like

Adding custom foods to increase fatigue (like when I drink a cup of rose tea to make me want to go to sleep）

**Comment by Su5eD** [comment]
This is already possible via the `replenishingItems` config option, on both 1.12 and 1.16 versions of the mod

**Comment by nitbe** [comment]
> 这已经可以通过`replenishingItems`config 选项在 1.12 和 1.16 版本的 mod 上实现
It seems that only fatigue values ​​can not be deducted
If I want to increase the fatigue value I should  [tea_kettle:black_latte, -10]？
It seems that it doesn't work
