### ISSUE TITLE
Suffocating in walls while sleeping in specific positions

### ISSUE THREAD

**Issue by aipimfrito** [Su5eD/Somnia-Awoken#66]
### What version were you using?
       
       Minecraft version 1.12.2
       Somnia Awoken version 1.10.2
       Forge version 14.23.5.2855

### Describe the bug

When sleeping in the position shown in the image linked below (Link 1), the player will start suffocating and die when they sleep. Only that specific block position will cause the bug, and the pillow needs to be facing west or north. If it is facing west, any blocks directly to the left (south) of the pillow will cancel the bug, and if facing north, the same thing happens for blocks at the right (east) of the pillow.

### Is this bug related to another mod?

I haven't checked yet, nor have I much experience with mod conflicts and such, but I don't think any of the mods I'm using are influencing this. My mod folder is linked below (Link 3), just to guarantee.

### Steps to reproduce

1. Reproduce the setup in Link 1: place the bed with the pillow facing north or west and, one block behind the pillow, make a pillar 3 block tall (the important part is the 3rd block); make sure to have no blocks in the sides of the pillow
2. Sleep in Survival mode
3. Suffocate to death

### Expected Behavior

Sleep normally without dying

### Additional context

Link 1: https://drive.google.com/file/d/1XwtyN7nRFuXOy11P_Wdq0qs4R0LAcEx5/view?usp=sharing
Link 2: https://drive.google.com/file/d/1r1jJFTV-PwwzoWw-fVkGt-StBB4GMlvw/view?usp=sharing (in this example, the bed is facing west)
Link 3: https://drive.google.com/file/d/1lzffxsWr2DoBxSVmc0h-nHwZbctHiSJy/view?usp=sharing

**Comment by aipimfrito** [comment]
wait I accidentally uploaded it, i'll finish it

**Comment by Su5eD** [comment]
Hi, I'll be closing this issue as the support for 1.12 releases is ending, with 1.16 the new LTS version. If you are able to reproduce this issue in newer versions, feel free to open a new issue and I'll look for a solution. Thanks!
