### ISSUE TITLE
Bed Explosion Removal Config

### ISSUE THREAD

**Issue by UberbeastX** [Su5eD/Somnia-Awoken#69]
### Is your feature request related to a problem? Please describe.

I need to sleep in other dimensions but the bed just explodes

### Describe the solution you'd like

I just want a config that disables exploding beds so I can sleep in the into the maelstrom mod dimensions

### Additional context

Honestly think this should be a feature of this mod since it makes you require sleep and, you will have adventures in other dimensions pretty often in modded playthroughs, so removing a limit in sleep would be good.

**Comment by Su5eD** [comment]
This could be done, but the issue with sleeping in unnatural dimensions (nether/end) is that they don't have a day/night cycle, so you can't simulate the world with a target wake time. Or if you just need to decrease your fatigue, maybe you could bring a few coffees or an awakening potion with you?

**Comment by Su5eD** [comment]
Closing as stale
