### ISSUE TITLE
With Mahou Tsukai installed, mana use increases but not mana regen when sleeping

### ISSUE THREAD

**Issue by aaronhowser1** [Su5eD/Somnia-Awoken#7]
https://cdn.discordapp.com/attachments/624786369629126666/741796035722215444/2020-08-08_18-09-41.mp4

**Comment by Su5eD** [comment]
What time was it?

**Comment by stepsword** [comment]
Hi,

I'm Mahou dev,

This is likely cause the mana regen is done by doing something like 

if(world.getTotalWorldTime() % 100 == 0)
     regenMana()

I had to change it to this from just using world.getWorldTime() cause some dimensions freeze time and mana regen would regen infinitely in those dimensions.

I doubt it's fixable and it'd probably be easier to just fire PlayerWakeUpEvent after the sleep, if you're not already

**Comment by Su5eD** [comment]
Thanks for the explanation. Somnia lets vanilla handle the sleep wherever possible, including wakeup. `EntityPlayer#wakeUpPlayer` is called, which fires the said PlayerWakeUpEvent. @aaronhowser1 did the mana regen when you woke up?

**Comment by stepsword** [comment]
I believe I also check the time they wake up (to make sure its morning) so it's possible it only regens sometimes, but that's not that big of a deal I'd say

**Comment by aaronhowser1** [comment]
Yes, the mana started regenning when I woke up. Or rather, it stopped getting used faster. It was still regenning when I was sleeping, it's just that it was getting used faster
