### ISSUE TITLE
Sleeping On Assembled Valkyrien Skies Ships Breaks Things(In the mod you're normally not able to sleep on assembled ships at all)

### ISSUE THREAD

**Issue by UberbeastX** [Su5eD/Somnia-Awoken#72]
### Describe the bug

I'm able to sleep on a Valkyrien Skies Ship and it just messes up everything

### Is this bug related to another mod?

Yes, Valkyrien Skies a ship mod that allows you to have dynamic ships that you can fight and walk on.

### Steps to reproduce

1. Make Valkyrien Skies airship or boat
2. Put bed on boat and sleep
3. See everything start messing up

### Expected Behavior

What's supposed to happen is that when you try to sleep on valkyrien skies ships it just sets your spawn to that ship and you can't really sleep, but since somnia modifies the way sleeping works you're able to sleep on the ship and since valkyrien skies isn't made for that it messes up the game. 

### Additional context

I'd just request a way to make it so sleeping isn't possible on Valkyrien Skies ships like it is in the mod normally since I can sleep with the mod if I disassemble the ship, but I wouldn't wanna accidentally sleep while it's assembled and mess everything up and would rather just have the option to sleep while it's assembled be taken away entirely.

**Comment by Su5eD** [comment]
Hi, I'll be closing this issue as the support for 1.12 releases is ending, with 1.16 the new LTS version. If you are able to reproduce this issue in newer versions, feel free to open a new issue and I'll look for a solution. Thanks!
