### ISSUE TITLE
Sleeping with low ceiling

### ISSUE THREAD

**Issue by Tskuno** [Su5eD/Somnia-Awoken#73]
### Describe the bug

If you load up 1.12.2 with this mod, and then try to sleep(not the right click sleep, the Somnia sleep that speeds time up) and the ceiling is less than 2 blocks above the floor you will take damage.

### Is this bug related to another mod?

No.

### Steps to reproduce

1. Make a world in creative in 1.12.2 with Somnia loaded
2. Find any ground, give yourself a bed, place the bed down
3. from the head of the bed, place blocks right behind it, 3 total, then make a ceiling that extends out so that the ceiling covers the bed from a top-down view.
4. Become Sleepy
5. Sleep in your bed with Somnia sleep(regular sleep is fine)
6. Die because you suffocate.
...

### Expected Behavior

Suffocation in your sleep. Pissed the mob off it seems...I can provide a fun video of dying. I've even done an entirely fresh install with JUST somnia in 1.12.2 so..

**Comment by Tskuno** [comment]
obviously set yourself in survival. forgot that step

**Comment by Tskuno** [comment]
You actually don't even need the wall behind the bed, it's specifically the two-block high ceiling. It's as if you're standing ontop of the bed despite the FOV suggesting otherwise.

**Comment by Tskuno** [comment]
![2022-04-27_20 12 18](https://user-images.githubusercontent.com/88564910/165651111-9043f4d5-38a1-4e32-b91c-1d61ddfc0bf0.png)

**Comment by Su5eD** [comment]
Hi, I'll be closing this issue as the support for 1.12 releases is ending, with 1.16 the new LTS version. If you are able to reproduce this issue in newer versions, feel free to open a new issue and I'll look for a solution. Thanks!

**Comment by Tskuno** [comment]
So in other words, you aren't going to fix this... The modpack I've been making can't go above 1.1.2.2 so I was hoping for a fix. May I attempt to fix this issue then? As in, can I have permission to rework this mod so it works.

**Comment by Su5eD** [comment]
Yeah, feel free to submit a fix

**Comment by Tskuno** [comment]
do you have a link to the 1.12.2 on here? I can't seem to find it

**Comment by Su5eD** [comment]
Old branches were moved to [Su5eD/Somnia](https://github.com/Su5eD/Somnia).
