### ISSUE TITLE
Mod requires 'koremods' but it is already installed

### ISSUE THREAD

**Issue by Waoweens** [Su5eD/Somnia-Awoken#77]
### Describe the bug

The game says you need koremods version 0.4.7 or above, but it is already installed

### Is this bug related to another mod?

koremods

### Steps to reproduce

1. Install Somnia and Koremods
2. Launch the game
3. see dependency error

### Expected Behavior

The game launches fine

### Additional context

![image](https://user-images.githubusercontent.com/30313089/178735689-69ce9740-09e9-429e-9182-999ee81a9dde.png)

[Log and crash report](https://gist.github.com/Waoweens/1696f13f39094369702ed551eb95a43e)

arch btw
Forge 40.1.60
Somnia Awoken 1.18.2-3.0.1
Koremods 0.4.7

**Comment by Su5eD** [comment]
Seems to be caused by the forge version, 40.1.59 works fine. Will look into it
