### ISSUE TITLE
[Request] compat for modded beds

### ISSUE THREAD

**Issue by gatoborrachon** [Su5eD/Somnia-Awoken#8]
beds like the Cryogenic Chamber from Galacticraft, or the bed cart from railcraft, and many "vanilla" beds from other mods (like Industrial Renewal, Heat and Climate, etc) 

idk if its easy to add this compat, if it becomes really hard no problem, its an amazing mod anyways.

**Comment by gatoborrachon** [comment]
i forgot to say that what i mean with compat is for the clock, when you right-click these beds there's no gui for select when you will wake up, you just sleep.

**Comment by Su5eD** [comment]
Looks like they're not only incompatible, but bugged as well. I'll try to fix this ASAP.

**Comment by Su5eD** [comment]
Galacticraft re-implements the whole sleeping mechanism, what bugs Somnia (especially the fatigue and armor checks, and waking up). This has now been fixed, but world simulation and wake time selection don't work.

**Comment by Su5eD** [comment]
Support for Railcraft's Bed Cart has been added, including wake time selection

**Comment by Su5eD** [comment]
Beds from Industrial Renewal & Heat and Climate are supported automatically.
