### ISSUE TITLE
Can't add modded Effects to sideEffectStages

### ISSUE THREAD

**Issue by FernoXL** [Su5eD/Somnia-Awoken#82]
### Describe the bug

The Somnia-common config file allows one to change the side effects at each stage of fatigue. The issue is the use of Numerical Effect IDs isn't good for modded effects as Numerical IDs can shift and will shift around based on the world and the load order of mods. Using names Is a Better Choice.

### Is this bug related to another mod?

No

### Steps to reproduce

1. Download the mod and launch the game.
2. Open the config folder and the Somnia-common config file.
3. Try to add a modded effect by name (because the Numerical ID changes).
4. Crash.

### Expected Behavior

Using the Modded Effect's name to change the sideEffectStages would actually work.

### Additional context

Minecraft 1.18.2

**Comment by Su5eD** [comment]
Thanks for bringing this up, I should've abandoned IDs back in 1.16... The `sideEffectStages` will use registry names from now on. I've also included an automatic migration function to convert the IDs and overwrite the config file, ensuring backwards compatibility.
