### ISSUE TITLE
Server Crashing with PlayerRevive and This Mod 1.18.2

### ISSUE THREAD

**Issue by FernoXL** [Su5eD/Somnia-Awoken#86]
### Describe the bug

When on a server with Somnia Awoken and PlayerRevive, Being revived and going to sleep will cause the server to crash.

### Is this bug related to another mod?

Yes. PlayerRevive Puts you in a state of Down but not out when you die

### Steps to reproduce

1. Have Fatigue Over the level required for effects
2. Enter the Down but not out state of PlayerRevive
3. Sleep in a bed
4. Crash

### Expected Behavior

Expect to sleep.

### Additional context

https://pastebin.com/ET6HSxNe

https://www.curseforge.com/minecraft/mc-mods/playerrevive

**Comment by Su5eD** [comment]
Fixed in 52bffdd
