### ISSUE TITLE
[Issue] strange render when you sleep

### ISSUE THREAD

**Issue by gatoborrachon** [Su5eD/Somnia-Awoken#9]
when you go to sleep this happens:

![2020-08-09_10 32 34](https://user-images.githubusercontent.com/61126174/89736058-6a983e80-da2c-11ea-8bf6-d7d69df79cdb.png)
*placing a bed*

![2020-08-09_10 32 50](https://user-images.githubusercontent.com/61126174/89736068-75eb6a00-da2c-11ea-8e72-f34d998b43a8.png)
*the bug*

here is a crash report with all the mods i have, this crash has nothing with the bug, its just to show you the mods i have and see if probably its caused by one of these:
https://pastebin.com/dqngyd14

**Comment by Su5eD** [comment]
This is intentional, but can be disabled in the config (option `vanillaBugFixes`). Due to a bug, when sleeping, you always face north. Somnia doesn't even re-implement the sleep mechanic anymore, so the cause remains a mystery.

**Comment by juraj-hrivnak** [comment]
@Su5eD Would be cool to have this issue pinned. Because it's a common issue that lots of people might run into it.

**Comment by EdroCode** [comment]
I dont get it, how i resolve that

**Comment by Su5eD** [comment]
> can be disabled in the config (option `vanillaBugFixes`)

**Comment by EdroCode** [comment]
where is that
