### ISSUE TITLE
[1.18.2]When I disable fatigue side effects, I can't sleep.

### ISSUE THREAD

**Issue by ghost** [Su5eD/Somnia-Awoken#90]
### Describe the bug

When I disable fatigue side effects, I can't sleep.

### Is this bug related to another mod?

No.

### Steps to reproduce

1.Change the config.
2.Start the game, the value of fatigue displayed on the interface is 0.
3.When I right click on the bed, it works normally.
4.When I right click on the bed for the second time, the value of fatigue displayed on the interface is NaN, a message appears with the content of "You're not tired yet".

### Expected Behavior

I hope that the rules related to fatigue can be prohibited while keeping other rules.

### Additional context

Here is the link of my config.
https://gist.github.com/sweetymajo/ed6c4b92d4b855548072006161be7865

**Comment by Su5eD** [comment]
I was able to fix the issue, sleep should work fine now without fatigue building up.  
Also `timings.validSleepEnd` appears to be broken in your config, preventing acceleration from starting at all. Setting it back to `24000` will do the trick.
