### ISSUE TITLE
Hide fatigue meter 

### ISSUE THREAD

**Issue by Bigred200** [Su5eD/Somnia-Awoken#96]
### Is your feature request related to a problem? Please describe.

its just kinda annoying since i have fatigue disabled anyways 

### Describe the solution you'd like

Just a way to disable the meter showing up. Running on 1.16.5. Thanks!

**Comment by Su5eD** [comment]
Hi, unfortunately 1.16.5 is no longer supported. Please upgrade to a newer version to receive support.
