### ISSUE TITLE
"You're not tired yet"

### ISSUE THREAD

**Issue by Aceplante** [Su5eD/Somnia-Awoken#97]
### Describe the bug

This seems grammatically awkward

### Is this bug related to another mod?

no

### Steps to reproduce

Use this mod

### Expected Behavior

"You are not tired yet"

### Additional context

Even if technically grammatically correct, it seems awkward as that is not the way most would say that. With the suggested message above, it would also be more consistent with other messages in the game such as "you cannot sleep yet there are monsters nearby" for example.

**Comment by Su5eD** [comment]
I've done some research and it seems like the sentence is correct.
> No, the sentence "You're not tired yet" is not grammatically awkward. It is a common and acceptable use of the contraction "you're," which is a shortened version of "you are." The contraction "you're" is widely used in both spoken and written English and is considered appropriate in most contexts. Therefore, the sentence is grammatically correct and sounds natural.

So I think it comes down to personal choice. If you prefer not using the contraction, I'd recommend creating a resource pack and overriding the language file. It might take a bit of effort but it's all customizable.

**Comment by Aceplante** [comment]
Yes, "you're" is the proper conjunction of "you" and "are" but i just meant it doesn't sound right in that context. You dont need to always conjugate them any time the words appear together, and I dont know if english is your first langue or not but I dont think many people would say it that way. In the end it is your choice i guess
